version: '2'

services:
  jupyter:
    build: 
      context: .
    command: start-notebook.sh --NotebookApp.token=''        
    volumes: 
      - ".:/home/jovyan/work"
    ports: 
      - "8888:8888"